[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "explorer.exe"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 10000

[terminal.shell]
program = "pwsh.exe"

[window]
decorations = "Buttonless"
dynamic_title = false
opacity = 0.85
title = "Alacritty"

[window.padding]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = false

[general]
live_config_reload = true
working_directory = "~"
import = []

[terminal]
